global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
